volumes:
  gems_library_backend:

networks:
  net_library_backend:

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    networks: 
      - net_library_backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - gems_library_backend:/usr/local/bundle
      - .:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks: 
      - net_library_backend
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
